insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (82, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 92, 'Termite Control', 97);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (40, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 7, 'Sitework & Site Utilities', 51);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (54, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 58, 'EIFS', 70);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (89, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 83, 'Drilled Shafts', 55);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (33, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 36, 'Doors, Frames & Hardware', 96);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (27, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 85, 'Soft Flooring and Base', 39);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (81, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 79, 'Site Furnishings', 44);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 89, 'Plumbing & Medical Gas', 89);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (75, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 80, 'Construction Clean and Final Clean', 16);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 54, 'Site Furnishings', 35);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (58, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 14, 'Epoxy Flooring', 97);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (34, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 15, 'Framing (Steel)', 18);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (30, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 65, 'Retaining Wall and Brick Pavers', 100);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (28, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 26, 'Site Furnishings', 10);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (42, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 15, 'Electrical and Fire Alarm', 73);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (69, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 52, 'Structural and Misc Steel (Fabrication)', 70);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (95, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 31, 'Epoxy Flooring', 31);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (8, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 65, 'Doors, Frames & Hardware', 24);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (36, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 18, 'HVAC', 80);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (84, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 49, 'Drywall & Acoustical (MOB)', 37);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (54, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 83, 'Framing (Wood)', 47);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (79, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 85, 'Electrical and Fire Alarm', 91);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 81, 'Structural & Misc Steel Erection', 41);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (51, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 36, 'Rebar & Wire Mesh Install', 44);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (21, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 57, 'Termite Control', 73);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (73, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 61, 'Termite Control', 63);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (80, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 7, 'Ornamental Railings', 30);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (20, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 61, 'Marlite Panels (FED)', 50);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (15, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 73, 'Overhead Doors', 1);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (45, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 100, 'Hard Tile & Stone', 28);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (27, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 70, 'Exterior Signage', 90);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (26, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 59, 'Structural and Misc Steel (Fabrication)', 95);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (67, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 72, 'Fire Protection', 58);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (85, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 18, 'Epoxy Flooring', 49);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (77, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 8, 'Drilled Shafts', 79);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (28, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 44, 'RF Shielding', 53);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 13, 'Drywall & Acoustical (FED)', 51);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (56, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 45, 'Rebar & Wire Mesh Install', 35);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (14, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 33, 'Fire Protection', 39);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (43, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 49, 'Roofing (Asphalt)', 63);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (21, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 51, 'Overhead Doors', 68);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (22, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 63, 'Plumbing & Medical Gas', 60);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (17, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 79, 'Fire Sprinkler System', 20);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (20, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 67, 'Marlite Panels (FED)', 100);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (39, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 97, 'Elevator', 38);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (45, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 77, 'Sitework & Site Utilities', 34);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (23, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 74, 'Masonry', 39);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (85, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 30, 'EIFS', 15);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (43, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 93, 'Wall Protection', 98);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (51, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 27, 'Electrical and Fire Alarm', 17);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (62, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 20, 'Framing (Wood)', 77);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (92, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 25, 'Plumbing & Medical Gas', 54);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (30, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 100, 'Hard Tile & Stone', 48);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (80, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 73, 'Casework', 28);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (12, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 33, 'Roofing (Asphalt)', 58);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (31, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 99, 'Fire Protection', 1);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (48, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 33, 'Overhead Doors', 36);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (7, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 61, 'Epoxy Flooring', 84);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (51, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 40, 'Construction Clean and Final Clean', 37);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (22, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 11, 'Sitework & Site Utilities', 68);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (13, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 99, 'RF Shielding', 83);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 35, 'Soft Flooring and Base', 79);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (14, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 61, 'Retaining Wall and Brick Pavers', 91);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (79, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 4, 'Casework', 88);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (70, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 53, 'Painting & Vinyl Wall Covering', 54);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (62, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 66, 'Ornamental Railings', 92);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (29, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 56, 'Roofing (Asphalt)', 24);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (79, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 14, 'Granite Surfaces', 14);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (27, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 57, 'Rebar & Wire Mesh Install', 2);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (93, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 71, 'Termite Control', 95);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (81, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 25, 'Masonry', 86);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (29, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 91, 'Drywall & Acoustical (MOB)', 52);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (51, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 1, 'Electrical and Fire Alarm', 96);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (30, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 29, 'Structural and Misc Steel (Fabrication)', 36);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (14, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 77, 'Asphalt Paving', 10);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (96, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 49, 'Sitework & Site Utilities', 18);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (35, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 50, 'Waterproofing & Caulking', 78);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (29, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 37, 'Hard Tile & Stone', 72);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (76, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 78, 'Doors, Frames & Hardware', 79);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (67, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 40, 'Temp Fencing, Decorative Fencing and Gates', 33);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (7, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 7, 'Masonry & Precast', 43);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (94, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 15, 'Drywall & Acoustical (MOB)', 20);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (7, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 47, 'Asphalt Paving', 11);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (24, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 6, 'Wall Protection', 43);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (55, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 28, 'Masonry', 33);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (72, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 24, 'Roofing (Metal)', 26);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (57, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 91, 'Termite Control', 98);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (95, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 98, 'Glass & Glazing', 28);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (59, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 21, 'Roofing (Metal)', 92);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (9, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 50, 'Doors, Frames & Hardware', 66);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 68, 'Sitework & Site Utilities', 76);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (69, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 7, 'Soft Flooring and Base', 27);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (52, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 99, 'Wall Protection', 49);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (27, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 17, 'Sitework & Site Utilities', 67);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (67, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 31, 'Landscaping & Irrigation', 91);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (64, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 10, 'Sitework & Site Utilities', 64);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (87, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 68, 'Structural and Misc Steel (Fabrication)', 65);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (6, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 82, 'Rebar & Wire Mesh Install', 76);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (43, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 90, 'Glass & Glazing', 75);
insert into producto (id_vendedor, descripcion, costo, categoria, unidades) values (87, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 42, 'Exterior Signage', 22);
