insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (47, 'Brainverse', 'Profit-focused asynchronous access', 46.17, 'Epoxy Flooring', 28);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (30, 'Tagcat', 'Re-engineered neutral moderator', 60.96, 'Painting & Vinyl Wall Covering', 93);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (39, 'Twinte', 'Synergistic optimizing customer loyalty', 30.76, 'Framing (Steel)', 30);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (54, 'Divavu', 'Polarised bandwidth-monitored paradigm', 50.32, 'Fire Protection', 89);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (42, 'Centimia', 'Digitized attitude-oriented superstructure', 52.46, 'Sitework & Site Utilities', 61);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (32, 'Pixope', 'Customizable incremental website', 18.2, 'Construction Clean and Final Clean', 42);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (4, 'Topicblab', 'Team-oriented full-range toolset', 42.04, 'Plumbing & Medical Gas', 99);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (4, 'Oyope', 'Polarised discrete database', 83.46, 'Retaining Wall and Brick Pavers', 64);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (1, 'Yodo', 'Profound demand-driven project', 77.35, 'Electrical and Fire Alarm', 99);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (31, 'Tagfeed', 'Implemented mission-critical internet solution', 60.68, 'Prefabricated Aluminum Metal Canopies', 15);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (31, 'Tambee', 'Triple-buffered asymmetric instruction set', 15.36, 'HVAC', 7);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (42, 'Twinte', 'Progressive analyzing service-desk', 34.31, 'Rebar & Wire Mesh Install', 58);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (13, 'DabZ', 'Self-enabling clear-thinking database', 44.79, 'Plumbing & Medical Gas', 95);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (34, 'Oyoba', 'Polarised holistic synergy', 78.94, 'Asphalt Paving', 68);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (16, 'Tazzy', 'Versatile dynamic toolset', 92.16, 'Exterior Signage', 90);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (81, 'Aimbo', 'Decentralized user-facing time-frame', 35.93, 'Structural and Misc Steel (Fabrication)', 16);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (8, 'Oyoyo', 'Enhanced encompassing pricing structure', 29.26, 'Asphalt Paving', 20);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (63, 'Omba', 'Digitized optimal ability', 46.33, 'Electrical and Fire Alarm', 90);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (32, 'Pixoboo', 'Proactive responsive leverage', 70.91, 'Fire Protection', 51);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (43, 'Gabcube', 'Versatile 24 hour customer loyalty', 2.89, 'Masonry & Precast', 45);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (65, 'Rhynyx', 'Cloned clear-thinking access', 32.47, 'Masonry', 42);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (88, 'Babbleblab', 'Operative analyzing leverage', 44.38, 'Construction Clean and Final Clean', 35);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (34, 'Gigazoom', 'Open-architected directional contingency', 17.3, 'HVAC', 78);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (44, 'Twitterlist', 'Cross-group scalable paradigm', 92.83, 'Drywall & Acoustical (MOB)', 56);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (89, 'Linklinks', 'Mandatory optimal groupware', 22.06, 'Rebar & Wire Mesh Install', 13);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (12, 'Wikizz', 'Digitized incremental complexity', 78.18, 'Hard Tile & Stone', 76);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (91, 'Shufflebeat', 'Distributed non-volatile neural-net', 11.5, 'Fire Sprinkler System', 94);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (24, 'Skivee', 'User-friendly zero defect database', 70.46, 'RF Shielding', 77);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (85, 'Avamm', 'User-centric web-enabled software', 14.21, 'Waterproofing & Caulking', 45);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (35, 'Linktype', 'Digitized optimal archive', 85.5, 'Masonry', 8);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (16, 'Eazzy', 'Future-proofed 3rd generation model', 94.72, 'Doors, Frames & Hardware', 26);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (76, 'Avavee', 'Monitored tertiary help-desk', 79.72, 'Glass & Glazing', 48);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (27, 'Tagtune', 'Vision-oriented mobile support', 5.71, 'Landscaping & Irrigation', 80);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (42, 'Skipstorm', 'Object-based regional database', 72.23, 'Painting & Vinyl Wall Covering', 32);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (2, 'Thoughtbeat', 'Proactive homogeneous data-warehouse', 97.66, 'HVAC', 5);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (84, 'JumpXS', 'Distributed methodical functionalities', 83.13, 'Exterior Signage', 97);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (23, 'Demivee', 'Switchable asymmetric access', 5.57, 'Construction Clean and Final Clean', 47);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (92, 'Eare', 'Switchable reciprocal alliance', 27.01, 'Hard Tile & Stone', 24);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (50, 'Meejo', 'Adaptive eco-centric website', 81.69, 'Prefabricated Aluminum Metal Canopies', 99);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (27, 'Divape', 'Synchronised executive policy', 29.42, 'HVAC', 79);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (49, 'Zoomcast', 'Inverse methodical function', 71.45, 'Structural and Misc Steel (Fabrication)', 4);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (23, 'InnoZ', 'Enhanced clear-thinking open system', 91.74, 'Temp Fencing, Decorative Fencing and Gates', 12);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (55, 'Blogtag', 'Versatile dedicated parallelism', 41.35, 'EIFS', 63);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (83, 'Topicblab', 'Team-oriented mission-critical knowledge base', 88.57, 'EIFS', 46);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (17, 'Youspan', 'Enhanced dedicated array', 88.25, 'Prefabricated Aluminum Metal Canopies', 21);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (13, 'Digitube', 'Reduced intangible installation', 72.96, 'Prefabricated Aluminum Metal Canopies', 38);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (26, 'Innojam', 'Monitored empowering throughput', 26.73, 'Soft Flooring and Base', 4);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (54, 'Nlounge', 'Focused 24 hour database', 61.96, 'Masonry', 78);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (55, 'Rhyloo', 'Customizable client-driven flexibility', 10.36, 'Ornamental Railings', 55);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (4, 'Jabbersphere', 'Profit-focused optimal core', 62.02, 'Waterproofing & Caulking', 25);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (53, 'Aimbu', 'Centralized asymmetric capacity', 45.74, 'Framing (Wood)', 11);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (55, 'Tagcat', 'Public-key discrete forecast', 45.4, 'Construction Clean and Final Clean', 37);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (18, 'Wikizz', 'Mandatory 6th generation conglomeration', 51.97, 'Landscaping & Irrigation', 4);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (32, 'Quinu', 'Monitored national encryption', 29.99, 'Termite Control', 44);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (2, 'Voomm', 'Function-based encompassing methodology', 74.2, 'Site Furnishings', 63);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (92, 'Abata', 'Down-sized intermediate focus group', 58.69, 'Masonry & Precast', 48);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (31, 'Dabtype', 'Up-sized user-facing workforce', 22.49, 'Structural & Misc Steel Erection', 11);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (52, 'Yakijo', 'Profit-focused coherent process improvement', 64.68, 'Wall Protection', 94);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (6, 'Leexo', 'Synergistic attitude-oriented matrix', 29.66, 'Framing (Steel)', 12);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (98, 'Quimm', 'Adaptive fresh-thinking hub', 23.08, 'Casework', 5);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (97, 'Bluezoom', 'Operative responsive paradigm', 65.2, 'Retaining Wall and Brick Pavers', 48);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (98, 'Wordtune', 'Configurable scalable throughput', 36.99, 'Drilled Shafts', 26);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (48, 'Gabtype', 'Seamless demand-driven help-desk', 23.84, 'Drilled Shafts', 31);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (90, 'Quatz', 'Extended even-keeled task-force', 65.88, 'Fire Sprinkler System', 98);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (47, 'Eimbee', 'Triple-buffered optimal forecast', 19.71, 'Drilled Shafts', 75);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (54, 'Jabbertype', 'Expanded zero tolerance budgetary management', 74.94, 'Painting & Vinyl Wall Covering', 65);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (94, 'Shuffledrive', 'Universal systematic paradigm', 24.56, 'Wall Protection', 67);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (98, 'LiveZ', 'Robust tangible methodology', 59.92, 'Retaining Wall and Brick Pavers', 28);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (53, 'Youopia', 'Self-enabling scalable Graphical User Interface', 93.09, 'Elevator', 92);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (20, 'Eimbee', 'Adaptive directional internet solution', 82.06, 'Framing (Wood)', 39);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (36, 'Yodel', 'Optimized didactic concept', 34.72, 'Retaining Wall and Brick Pavers', 53);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (52, 'Gigazoom', 'Team-oriented radical data-warehouse', 26.35, 'Hard Tile & Stone', 2);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (84, 'Yombu', 'Exclusive 24 hour software', 33.09, 'Site Furnishings', 52);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (24, 'Skivee', 'Multi-layered needs-based instruction set', 74.74, 'Masonry & Precast', 70);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (92, 'Flashspan', 'Implemented 24/7 orchestration', 13.42, 'Curb & Gutter', 22);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (98, 'Brainlounge', 'Inverse reciprocal open architecture', 21.91, 'Electrical', 90);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (70, 'Lazz', 'Diverse analyzing strategy', 83.22, 'Roofing (Asphalt)', 18);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (91, 'Zoomcast', 'Horizontal cohesive moderator', 39.75, 'Marlite Panels (FED)', 96);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (81, 'Blogtag', 'Persistent bandwidth-monitored process improvement', 58.99, 'Drywall & Acoustical (FED)', 58);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (68, 'Jaxnation', 'Reduced context-sensitive framework', 36.08, 'Termite Control', 45);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (5, 'Mydeo', 'Multi-channelled optimizing open system', 94.09, 'Electrical and Fire Alarm', 87);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (78, 'Wikivu', 'Programmable human-resource portal', 30.83, 'Drilled Shafts', 41);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (53, 'Zoomdog', 'Exclusive hybrid forecast', 88.65, 'RF Shielding', 28);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (65, 'Edgeblab', 'Persevering 24/7 adapter', 18.66, 'Curb & Gutter', 12);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (8, 'Vinte', 'User-friendly modular conglomeration', 82.39, 'Construction Clean and Final Clean', 11);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (51, 'Rooxo', 'Mandatory neutral standardization', 55.02, 'Ornamental Railings', 23);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (38, 'Edgepulse', 'Cross-platform user-facing methodology', 40.16, 'Glass & Glazing', 12);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (41, 'Kwideo', 'Triple-buffered empowering emulation', 15.85, 'Elevator', 23);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (75, 'Voonyx', 'Diverse cohesive framework', 33.6, 'Sitework & Site Utilities', 76);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (75, 'Kaymbo', 'Multi-tiered fresh-thinking projection', 6.17, 'Roofing (Asphalt)', 99);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (11, 'Yakijo', 'Multi-tiered background focus group', 3.98, 'Curb & Gutter', 4);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (40, 'Gabcube', 'Enterprise-wide 24 hour website', 78.19, 'Roofing (Metal)', 32);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (1, 'Yodel', 'Operative methodical open architecture', 92.47, 'Glass & Glazing', 89);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (39, 'Quamba', 'Customizable fault-tolerant hardware', 23.85, 'Drywall & Acoustical (MOB)', 21);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (46, 'Quire', 'Object-based systemic moratorium', 7.71, 'Epoxy Flooring', 57);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (50, 'Skaboo', 'Horizontal client-server framework', 26.88, 'Painting & Vinyl Wall Covering', 31);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (76, 'Ooba', 'Programmable uniform initiative', 40.18, 'Prefabricated Aluminum Metal Canopies', 68);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (26, 'Centidel', 'Stand-alone discrete superstructure', 12.4, 'Construction Clean and Final Clean', 86);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (59, 'Zoonder', 'Open-architected background hardware', 91.06, 'Roofing (Asphalt)', 77);
insert into producto (id_vendedor, nombre, descripcion, costo, categoria, unidades) values (89, 'Jaxspan', 'Inverse demand-driven access', 5.62, 'Prefabricated Aluminum Metal Canopies', 17);
